### ISSUE TITLE
Line Notify Upload Image ("payload":"imageFile is invalid" )

### ISSUE THREAD

**Issue by HiDanny666** [jatu-studiobox/node-red-contrib-node-line-api#2]
here is my flow

https://pastebin.com/axGRDEjY

I imported the example FLOW in GITHUB, only changed the file location.

After I send it, it says "payload": "imageFile is invalid".

My environment is NODE-RED from Truenas, and I also tried ubuntu server, all with the same error.

I also installed NODE-RED on Windows, imported the same FLOW and changed the file location, and this time the pictures were 

successfully transferred.

Why is the transfer successful only on Windows?

error
`{"_msgid":"c72767f33d6ae038","payload":"imageFile is invalid","useImageFile":true,"imageFile":"/shared/image/111.jpg","useImageUrl":false,"status":-1}`

**Comment by jatu-studiobox** [comment]
Hi, first, thank you very much for your issue. :)

Now this issue has fixed at 0.8.7 or latest version.
